#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Gopath
export GOPATH=$HOME/go

# Path binaries from dotfiles
export PATH=$HOME/.dotfiles/bin:$PATH

# Path system wide go binaries
export PATH=/usr/local/go/bin:$PATH

# Path local go binaries
export PATH=$GOPATH/bin:$PATH

# Path local rust binaries
export PATH=$HOME/.cargo/bin:$PATH

# Path custom compiled alacritty
export PATH=$HOME/code/alacritty/target/release:$PATH

# True color in neovim
export NVIM_TUI_ENABLE_TRUE_COLOR=1

# Set FZF colorscheme
export FZF_DEFAULT_OPTS='
  --color=bg+:#282c34,bg:#21252a,spinner:#98c373,hl:#98c373
  --color=fg:#abb2c0,header:#abb2c0,info:#526270,pointer:#d19966
  --color=marker:#d19966,fg+:#abb2c0,prompt:#abb2c0,hl+:#d19966
'
