#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export TERM=rxvt-unicode-256color
export GOPATH=$HOME/gopath
export PATH=$HOME/.dotfiles/bin:$PATH:/usr/local/go/bin:$GOPATH/bin
export LD_LIBRARY_PATH=/usr/local/lib

# UCP/DTR exports
export UCP_USER=admin
export UCP_PASS=password
export UCP_PORT=444
export UCP_SWARM_PORT=3376
export UCP_LB_PORT=446

export DTR_PORT=443

export ETCD_CLIENT_PORT=2379

export CONSUL_PORT=8500
